#!/usr/bin/env python3
"""Generate the per-document VIEWS of the master register.

There is ONE register: deliverables/_control/master-register.csv. Every deliverable
carries a filtered view of it, generated here, so that an item cannot end up with two
different statuses in two documents. Views are never edited by hand.

Generates:
  deliverables/technical-manual/appendix-E-open-technical-questions.md   T + V items
  deliverables/_control/views/decisions-by-stage.md                      D items, for the SOP
  deliverables/_control/views/blocking.md                                anything blocking

    python3 tools/build-register-views.py
"""
import csv, os, re, datetime, collections

REG = 'deliverables/_control/master-register.csv'
VIEWS = 'deliverables/_control/views'
MANUAL = 'deliverables/technical-manual'

def load():
    return list(csv.DictReader(open(REG)))

def key(r):
    m = re.match(r'([DTV])-?(\d+)$', r['id'].strip())
    return ({'D': 0, 'T': 1, 'V': 2}[m.group(1)], int(m.group(2)))

def stamp(n):
    return (f'**{n} items.** Generated from `deliverables/_control/master-register.csv` on '
            f'{datetime.date.today().isoformat()}. **Do not edit this file** — edit the register '
            f'and re-run `tools/build-register-views.py`.')

def block(r):
    out = [f"### {r['id']} · {r['question']}", '']
    meta = [f"**{r['priority']}**", r['status']]
    if r['blocks_operation'].strip().lower() == 'yes':
        meta.append('**blocks operation**')
    if r['owner'].strip(): meta.append('owner: ' + r['owner'])
    out.append(' · '.join(meta))
    out.append('')
    if r['why_it_matters'].strip():
        out.append(f"**Why it matters.** {r['why_it_matters']}")
        out.append('')
    if r['source_evidence'].strip() and r['source_evidence'].strip() != '—':
        out.append(f"**Evidence.** {r['source_evidence']}")
        out.append('')
    tail = []
    if r['affected_stage'].strip(): tail.append(f"Stage: {r['affected_stage']}")
    if r['affected_documents'].strip(): tail.append(f"Documents: {r['affected_documents']}")
    if tail: out.append('*' + ' · '.join(tail) + '*'); out.append('')
    if r['resolution'].strip():
        out.append(f"> **Resolved {r['date_resolved']}.** {r['resolution']}")
        out.append('')
    return '\n'.join(out)

rows = load()

# ---- Manual Appendix E: the technical questions (tests and vendor questions) ----
tv = sorted([r for r in rows if r['type'] in ('test', 'vendor')], key=key)
tests = [r for r in tv if r['type'] == 'test']
vend  = [r for r in tv if r['type'] == 'vendor']
p1 = [r for r in tv if r['priority'] == 'P1']
blk = [r for r in tv if r['blocks_operation'].strip().lower() == 'yes']

e = [f"""# Appendix E — Open Technical Questions

{stamp(len(tv))}

This appendix is the Technical Manual's **view** of the project's single master register. It shows
the questions that are answerable by **evidence** — by running a test, or by asking Trimble. The
decisions that are Parametrix's to make are the SOP's view of the same register and are not
repeated here.

| | Count |
|---|---|
| **FIELD TESTING REQUIRED** — answerable by testing | **{len(tests)}** |
| **VENDOR CLARIFICATION REQUIRED** — answerable only by Trimble | **{len(vend)}** |
| Of those, priority P1 | {len(p1)} |
| Of those, blocking an operation | {len(blk)} |

> **An open item here is not a defect in this manual.** It is a statement that the evidence does
> not yet reach, recorded rather than papered over. Where a question is open, the body of the
> manual says so at the point where it matters, rather than presenting a guess as a fact.

---

## E1 · Field testing required

*Answerable with the equipment and the software. Each entry says what to do, not merely what is
unknown.*
"""]
for r in tests: e.append(block(r))
e.append("""---

## E2 · Vendor clarification required

*Not answerable from the documentation held. Each is a question for Trimble or for the dealer.*
""")
for r in vend: e.append(block(r))
e.append(f"""---

## E3 · Recording an answer

When one of these is answered, the answer goes into the **master register** —
`deliverables/_control/master-register.csv` — in the `resolution` and `date_resolved` columns, and
the status changes. Then re-run `tools/build-register-views.py`, and this appendix and every other
view update together.

Test results with detail worth keeping — numbers, conditions, what was and was not tried — go in
**Appendix F**, and the register entry points at them.

**Do not answer one of these by editing the manual body alone.** A statement changed in one place
and not in the register is exactly the drift this structure exists to prevent.
""")
os.makedirs(VIEWS, exist_ok=True)
open(os.path.join(MANUAL, 'appendix-E-open-technical-questions.md'), 'w').write('\n'.join(e))
print(f'Appendix E: {len(tv)} items ({len(tests)} tests, {len(vend)} vendor)')

# ---- SOP Appendix A: the decision register and the adoption record ----
SOPDIR = 'deliverables/sop'
dec_all = sorted([r for r in rows if r['type'] == 'decision'], key=key)
adopted = [r for r in dec_all if r['status'].strip().lower() == 'adopted']
blocking_d = [r for r in dec_all if r['blocks_operation'].strip().lower() == 'yes']
p1 = [r for r in dec_all if r['priority'] == 'P1']
a = [f"""# Appendix A — Parametrix Decision Register

{stamp(len(dec_all))}

This appendix is the SOP's **view** of the project's single master register. It shows the questions
that are **Parametrix's to answer** — the ones no test and no vendor can settle. The questions
answerable by evidence are the Technical Manual's Appendix E, and are not repeated here.

| | Count |
|---|---|
| Decisions open | **{len(dec_all) - len(adopted)}** |
| **Adopted** | **{len(adopted)}** |
| Priority P1 | {len(p1)} |
| Blocking an operation | {len(blocking_d)} |

> **CAUTION**
>
> **{'No decision has been adopted.' if not adopted else str(len(adopted)) + ' decisions have been adopted.'}**
> A clause in this SOP whose decision appears below as open is **not a Parametrix requirement**. It
> is a proposal from this project, and it may not be quoted to a client, a reviewer or a regulator
> as an existing Parametrix standard.

## A1 · The adoption record

A decision becomes binding when it appears here with an answer, a date and an approver — and when
the register is updated and the views regenerated. **Editing this appendix by hand does not adopt
anything**, because it is regenerated from the register.

| ID | Decision taken | Date | Approved by |
|---|---|---|---|"""]
for r in dec_all:
    if r['resolution'].strip():
        a.append(f"| **{r['id']}** | {r['resolution']} | {r['date_resolved']} | {r['owner'] or '—'} |")
if not adopted:
    a.append('| — | *No decision has been adopted at this revision.* | — | — |')
a.append(f"""

## A2 · Decisions that block operation

{len(blocking_d)} of the {len(dec_all)} decisions block an operation: work cannot proceed correctly
until they are settled, as distinct from work being harder without them.

| ID | Decision | SOP § |
|---|---|---|""")
SOPSEC = {'D-1':'2','D-2':'6.4','D-3':'4.2','D-10':'13.1','D-11':'13.1','D-12':'13.4','D-13':'16.2',
 'D-15':'7.3','D-16':'7.4','D-18':'12.2','D-19':'6.2','D-21':'6.2','D-22':'13.3','D-24':'14.3',
 'D-26':'14.2','D-27':'15.5','D-28':'14.6','D-29':'19.2','D-31':'15.6','D-32':'18.6','D-34':'8.6',
 'D-35':'17.2','D-36':'18.2','D-38':'18.4','D-39':'15.5','D-41':'8.2','D-42':'8.5','D-43':'9.4',
 'D-46':'9.1','D-49':'9.6','D-52':'11.2','D-53':'11.4','D-54':'11.5','D-55':'20.1'}
for r in blocking_d:
    a.append(f"| **{r['id']}** | {r['question']} | §{SOPSEC.get(r['id'],'—')} |")
a.append('\n## A3 · The full register\n')
for r in dec_all:
    b = block(r)
    b = b.replace('\n\n', f" · SOP §{SOPSEC.get(r['id'],'—')}\n\n", 1)
    a.append(b)
a.append("""---

## A4 · How a decision is adopted

1. Parametrix decides
2. The decision, its date and its approver are written into
   `deliverables/_control/master-register.csv` — `status`, `resolution`, `date_resolved`, `owner`
3. `python3 tools/build-register-views.py` regenerates this appendix and every other view
4. The SOP clause changes state from **PARAMETRIX DECISION REQUIRED** to **ADOPTED**, and its
   *should* becomes *shall*

**There is one register.** A decision cannot be adopted in one document and open in another.
""")
os.makedirs(SOPDIR, exist_ok=True)
open(os.path.join(SOPDIR, 'appendix-A-decision-register.md'), 'w').write('\n'.join(a))
print(f'SOP Appendix A: {len(dec_all)} decisions, {len(adopted)} adopted, {len(blocking_d)} blocking')

# ---- SOP view: decisions, grouped by workflow stage ----
dec = sorted([r for r in rows if r['type'] == 'decision'], key=key)
by = collections.OrderedDict()
for r in dec: by.setdefault(r['affected_stage'] or 'unassigned', []).append(r)
d = [f"""# View — Parametrix Decisions, by Workflow Stage

{stamp(len(dec))}

The decisions only Parametrix can make. This view is the source for the SOP's decision register.
"""]
for stage, rs in by.items():
    d.append(f'\n## {stage}\n')
    for r in rs: d.append(block(r))
open(os.path.join(VIEWS, 'decisions-by-stage.md'), 'w').write('\n'.join(d))
print(f'decisions-by-stage: {len(dec)} items in {len(by)} stages')

# ---- blocking view ----
b = [r for r in rows if r['blocks_operation'].strip().lower() == 'yes']
b.sort(key=key)
# Some blocking items are the same question raised from two directions (a Parametrix
# decision and the vendor question that would answer it). Group those explicitly.
SAME = [{'D-2', 'V-4'}]
qs = collections.OrderedDict()
for r in b:
    k = next((min(g) for g in SAME if r['id'] in g), r['id'])
    qs.setdefault(k, []).append(r)
out = [f"""# View — Items Blocking Operation

{stamp(len(b))}

An item is marked **blocking** when work cannot proceed correctly until it is settled — not merely
when it would be useful to know. {len(b)} rows, **{len(qs)} distinct questions**.
"""]
for _, rs in qs.items():
    if len(rs) > 1:
        out.append(f"> **{' and '.join(r['id'] for r in rs)} are the same question**, raised from "
                   f"different directions.\n")
    for r in rs: out.append(block(r))
open(os.path.join(VIEWS, 'blocking.md'), 'w').write('\n'.join(out))
print(f'blocking: {len(b)} rows, {len(qs)} distinct')
