#!/usr/bin/env python3
"""Generate the per-document VIEWS of the master register.

There is ONE register: deliverables/_control/master-register.csv. Every deliverable
carries a filtered view of it, generated here, so that an item cannot end up with two
different statuses in two documents. Views are never edited by hand.

Generates:
  deliverables/technical-manual/appendix-E-open-technical-questions.md   T + V items
  deliverables/_control/views/decisions-by-stage.md                      D items, for the SOP
  deliverables/_control/views/blocking.md                                anything blocking

    python3 tools/build-register-views.py
"""
import csv, os, re, datetime, collections

REG = 'deliverables/_control/master-register.csv'
VIEWS = 'deliverables/_control/views'
MANUAL = 'deliverables/technical-manual'

def load():
    return list(csv.DictReader(open(REG)))

def key(r):
    m = re.match(r'([DTV])-?(\d+)$', r['id'].strip())
    return ({'D': 0, 'T': 1, 'V': 2}[m.group(1)], int(m.group(2)))

def stamp(n):
    return (f'**{n} items.** Generated from `deliverables/_control/master-register.csv` on '
            f'{datetime.date.today().isoformat()}. **Do not edit this file** — edit the register '
            f'and re-run `tools/build-register-views.py`.')

def block(r):
    out = [f"### {r['id']} · {r['question']}", '']
    meta = [f"**{r['priority']}**", r['status']]
    if r['blocks_operation'].strip().lower() == 'yes':
        meta.append('**blocks operation**')
    if r['owner'].strip(): meta.append('owner: ' + r['owner'])
    out.append(' · '.join(meta))
    out.append('')
    if r['why_it_matters'].strip():
        out.append(f"**Why it matters.** {r['why_it_matters']}")
        out.append('')
    if r['source_evidence'].strip() and r['source_evidence'].strip() != '—':
        out.append(f"**Evidence.** {r['source_evidence']}")
        out.append('')
    tail = []
    if r['affected_stage'].strip(): tail.append(f"Stage: {r['affected_stage']}")
    if r['affected_documents'].strip(): tail.append(f"Documents: {r['affected_documents']}")
    if tail: out.append('*' + ' · '.join(tail) + '*'); out.append('')
    if r['resolution'].strip():
        out.append(f"> **Resolved {r['date_resolved']}.** {r['resolution']}")
        out.append('')
    return '\n'.join(out)

rows = load()

# ---- Manual Appendix E: the technical questions (tests and vendor questions) ----
tv = sorted([r for r in rows if r['type'] in ('test', 'vendor')], key=key)
tests = [r for r in tv if r['type'] == 'test']
vend  = [r for r in tv if r['type'] == 'vendor']
p1 = [r for r in tv if r['priority'] == 'P1']
blk = [r for r in tv if r['blocks_operation'].strip().lower() == 'yes']

e = [f"""# Appendix E — Open Technical Questions

{stamp(len(tv))}

This appendix is the Technical Manual's **view** of the project's single master register. It shows
the questions that are answerable by **evidence** — by running a test, or by asking Trimble. The
decisions that are Parametrix's to make are the SOP's view of the same register and are not
repeated here.

| | Count |
|---|---|
| **FIELD TESTING REQUIRED** — answerable by testing | **{len(tests)}** |
| **VENDOR CLARIFICATION REQUIRED** — answerable only by Trimble | **{len(vend)}** |
| Of those, priority P1 | {len(p1)} |
| Of those, blocking an operation | {len(blk)} |

> **An open item here is not a defect in this manual.** It is a statement that the evidence does
> not yet reach, recorded rather than papered over. Where a question is open, the body of the
> manual says so at the point where it matters, rather than presenting a guess as a fact.

---

## E1 · Field testing required

*Answerable with the equipment and the software. Each entry says what to do, not merely what is
unknown.*
"""]
for r in tests: e.append(block(r))
e.append("""---

## E2 · Vendor clarification required

*Not answerable from the documentation held. Each is a question for Trimble or for the dealer.*
""")
for r in vend: e.append(block(r))
e.append(f"""---

## E3 · Recording an answer

When one of these is answered, the answer goes into the **master register** —
`deliverables/_control/master-register.csv` — in the `resolution` and `date_resolved` columns, and
the status changes. Then re-run `tools/build-register-views.py`, and this appendix and every other
view update together.

Test results with detail worth keeping — numbers, conditions, what was and was not tried — go in
**Appendix F**, and the register entry points at them.

**Do not answer one of these by editing the manual body alone.** A statement changed in one place
and not in the register is exactly the drift this structure exists to prevent.
""")
os.makedirs(VIEWS, exist_ok=True)
open(os.path.join(MANUAL, 'appendix-E-open-technical-questions.md'), 'w').write('\n'.join(e))
print(f'Appendix E: {len(tv)} items ({len(tests)} tests, {len(vend)} vendor)')

# ---- SOP view: decisions, grouped by workflow stage ----
dec = sorted([r for r in rows if r['type'] == 'decision'], key=key)
by = collections.OrderedDict()
for r in dec: by.setdefault(r['affected_stage'] or 'unassigned', []).append(r)
d = [f"""# View — Parametrix Decisions, by Workflow Stage

{stamp(len(dec))}

The decisions only Parametrix can make. This view is the source for the SOP's decision register.
"""]
for stage, rs in by.items():
    d.append(f'\n## {stage}\n')
    for r in rs: d.append(block(r))
open(os.path.join(VIEWS, 'decisions-by-stage.md'), 'w').write('\n'.join(d))
print(f'decisions-by-stage: {len(dec)} items in {len(by)} stages')

# ---- blocking view ----
b = [r for r in rows if r['blocks_operation'].strip().lower() == 'yes']
b.sort(key=key)
# Some blocking items are the same question raised from two directions (a Parametrix
# decision and the vendor question that would answer it). Group those explicitly.
SAME = [{'D-2', 'V-4'}]
qs = collections.OrderedDict()
for r in b:
    k = next((min(g) for g in SAME if r['id'] in g), r['id'])
    qs.setdefault(k, []).append(r)
out = [f"""# View — Items Blocking Operation

{stamp(len(b))}

An item is marked **blocking** when work cannot proceed correctly until it is settled — not merely
when it would be useful to know. {len(b)} rows, **{len(qs)} distinct questions**.
"""]
for _, rs in qs.items():
    if len(rs) > 1:
        out.append(f"> **{' and '.join(r['id'] for r in rs)} are the same question**, raised from "
                   f"different directions.\n")
    for r in rs: out.append(block(r))
open(os.path.join(VIEWS, 'blocking.md'), 'w').write('\n'.join(out))
print(f'blocking: {len(b)} rows, {len(qs)} distinct')
